apiVersion: v1
kind: Secret
metadata:
  name: ess-matrix-authentication-service
  namespace: ess
data:
  user-enable-registration-smtp: "cGFzc3dvcmRzOgogIGVuYWJsZWQ6IHRydWUKZW1haWw6CiAgdHJhbnNwb3J0OiBzbXRwCiAgc210cDoKICAgIG1vZGU6IHN0YXJ0dGxzCiAgICBob3N0bmFtZTogInNtdHAueWFuZGV4LnJ1IgogICAgcG9ydDogNTg3CiAgICB1c2VybmFtZTogImdpOTlsaW5AeWFuZGV4LnJ1IgogICAgcGFzc3dvcmQ6ICJyanhoY2R5eXZnY2pxcXZkIgogICAgZnJvbTogImdpOTlsaW5AeWFuZGV4LnJ1Igo="
type: Opaque
