#!/usr/bin/expect -f
set timeout 30
set ip [lindex $argv 0]
set password [lindex $argv 1]

# Get the Secret content and decode it
# We select the specific key 'user-enable-registration-smtp' (based on pod args)
set cmd "export KUBECONFIG=/etc/rancher/k3s/k3s.yaml; kubectl get secret -n ess ess-matrix-authentication-service -o jsonpath='{.data}'"

spawn ssh -o StrictHostKeyChecking=no root@$ip $cmd
expect {
    "password:" { send "$password\r"; exp_continue }
    eof
}
