apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-hdd-pvc
  namespace: nextcloud
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: hdd-manual
  resources:
    requests:
      storage: 4Ti
